Update README.md
CirclesUBI/circles-docker pull request #30
Opened 2021-03-12 12:58 UTC by louilinn

Related issue: https://github.com/CirclesUBI/.github/issues/5

2021-03-16 11:41 UTC, adzialocha requested changes

2021-03-16 11:41 UTC, adzialocha commented on README.md
> +  </a>
This is pointing at the license of `circles-core`

2021-03-16 11:41 UTC, adzialocha commented on README.md
> +    <span> | </span>
This can be removed

2021-03-16 11:41 UTC, adzialocha commented on README.md
> +
Maybe we should remove the changelog here? We don't have any clear versioning for the `circles-docker` repo and maybe it is also not necessary?

2021-03-17 13:32 UTC, louilinn commented on README.md
> +  </a>
Since there is no license file in the docker repo, do you think I should add one or refer elsewhere?

2021-03-17 13:38 UTC, adzialocha commented on README.md
> +  </a>
Good point!

2021-03-18 14:35 UTC, merged