adding pathfinder2 services
CirclesUBI/circles-docker pull request #66
Opened 2023-01-18 16:22 UTC by JacqueGM

- adding pathfinder2 services

2023-01-18 20:51 UTC, almereyda commented on docker-compose.pathfinder-pull.yml
> +
I would suggest to eliminate the whitespace below before merging.

2023-01-18 21:19 UTC, almereyda requested changes
This came very well *together*, in the literate sense.

Let's please find a moment to consider the suggested code changes, and wait a bit until we can replace the image names with new permanent identifiers.

2023-01-18 21:19 UTC, almereyda commented on docker-compose.yml
>      env_file:
Would it feel suitable to replace this `env_file:` declarative in this row with an explicit `environment:` dictionary that explicitly passes only those variables from `.env`, which are actually needed? This is also more verbose, and thus readable, understandable and explicit.

```suggestion
    environment:
```

2023-01-18 21:19 UTC, almereyda commented on docker-compose.yml
>        - .env
```suggestion
      POSTGRES_DB:       ${POSTGRES_USER}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
```

2023-01-18 21:19 UTC, almereyda commented on docker-compose.pathfinder-pull.yml
> +      - ./0.sql:/docker-entrypoint-initdb.d/0.sql
```suggestion
      - ${PWD}/0.sql:/docker-entrypoint-initdb.d/0.sql
```

2023-01-18 21:19 UTC, almereyda commented on docker-compose.pathfinder-pull.yml
> +      - ./0.sql:/docker-entrypoint-initdb.d/0.sql
Look what we've found! Some whitespace hid at the end of the line.

2023-01-18 23:56 UTC, almereyda commented on docker-compose.pathfinder-pull.yml
> +    image: ghcr.io/circlesland/pathfinder2:1.4.0
Please choose your flavour:

- https://hub.docker.com/r/circlesubi/pathfinder2/tags

```suggestion
    image: docker.io/circlesubi/pathfinder2:feature-dockerfile
```

- https://github.com/CirclesUBI/pathfinder2/pkgs/container/pathfinder2

```suggestion
    image: ghcr.io/circlesubi/pathfinder2:feature-dockerfile
```

2023-01-18 23:57 UTC, almereyda commented on docker-compose.pathfinder-pull.yml
> +    image: ghcr.io/circlesland/pathfinder2-updater:0.1.1
Please choose your flavour:

- https://hub.docker.com/r/circlesubi/pathfinder2-updater/tags

```suggestion
    image: docker.io/circlesubi/pathfinder2-updater:dev
```

- https://github.com/CirclesUBI/pathfinder2/pkgs/container/pathfinder2

```suggestion
    image: ghcr.io/circlesubi/pathfinder2-updater:dev
```

2023-01-18 23:58 UTC, almereyda commented on docker-compose.pathfinder-pull.yml
> +    image: ghcr.io/circlesland/blockchain-indexer:0.0.67
Please choose your flavour:

- https://hub.docker.com/r/circlesubi/blockchain-indexer/tags

```suggestion
    image: docker.io/circlesubi/blockchain-indexer:dev
```

- https://github.com/CirclesUBI/blockchain-indexer/pkgs/container/blockchain-indexer

```suggestion
    image: ghcr.io/circlesubi/blockchain-indexer:dev
```

2023-01-19 00:01 UTC, almereyda commented
@jaensen also wanted to point your attention at the fact that there now is also a:

- https://github.com/CirclesUBI/pathfinder-proxy
  - https://github.com/CirclesUBI/pathfinder-proxy/pkgs/container/pathfinder-proxy
  - https://hub.docker.com/r/circlesubi/pathfinder-proxy/tags

I am sure they would be open to explain and introduce it in this round, in so this new Pathfinder setup is near currently possible feature completeness.

2023-01-24 13:46 UTC, llunaCreixent commented
Task: add the pathfinder-proxy for test it: https://hub.docker.com/orgs/circlesubi/repositories
https://github.com/CirclesUBI/pathfinder-proxy

2023-01-26 13:19 UTC, JacqueGM commented on docker-compose.pathfinder-pull.yml
> +  pathfinder2:
added

2023-01-31 15:44 UTC, llunaCreixent commented
Task:
- [ ] Add the env vars:

```
me says:WARNING: The POSTGRES_HOST variable is not set. Defaulting to a blank string.
WARNING: The POSTGRES_DATABASE_INDEXER_DB variable is not set. Defaulting to a blank string.
WARNING: The INDEXER_WS_URL variable is not set. Defaulting to a blank string.
WARNING: The INTERNAL_CAPACITY_GRAPH_PATH variable is not set. Defaulting to a blank string.
WARNING: The EXTERNAL_CAPACITY_GRAPH_PATH variable is not set. Defaulting to a blank string.
WARNING: The PATHFINDER_RPC_URL variable is not set. Defaulting to a blank string.
WARNING: The INDEXER_WEBSOCKET_URL variable is not set. Defaulting to a blank string.
WARNING: The INDEXER_RPC_GATEWAY_URL variable is not set. Defaulting to a blank string. 
```

2023-01-31 15:47 UTC, llunaCreixent commented
Task:
- [ ] add the `other-blockchain-user` like in here: https://github.com/CirclesUBI/land-local/blob/main/docker-compose.yml

So that the `pathfinder-updater` doesn't assume the system is unhealthy

2023-02-14 14:13 UTC, llunaCreixent commented on README.md
> +  grep -q "^127.0.0.1 relay.circles.lan$" /etc/hosts || echo "127.0.0.1 relay.circles.lan" | sudo tee -a /etc/hosts
Here it should say `circles.local`, right?

2023-02-14 14:17 UTC, llunaCreixent commented on README.md
> +make up API EXPOSE_PORTS=1 && make contracts && make subgraph && make up   EXPOSE_PORTS=1
Does the command doesn't need the `API` arg?

2023-02-14 15:53 UTC, llunaCreixent commented
when running the new docker compose, with my debian system, I get:
```
PermissionError: [Errno 13] Permission denied: '/home/CirclesUBI/circles-docker/.state/indexer-db/pg_data'
make: *** [Makefile:63: up] Error 1
```
```
$ ls -la /home/CirclesUBI/circles-docker/.state/indexer-db/
total 12
drwxr-xr-x  3 root             root 4096 Feb 14 15:35 .
drwxr-xr-x  4 root             root 4096 Feb 14 15:35 ..
drwx------ 19 systemd-coredump root 4096 Feb 14 16:03 pg_data
```

2023-02-27 22:29 UTC, almereyda commented
In https://github.com/CirclesUBI/circles-docker/commit/88de80c7563a5b0395b878986c37e693120b3323 this is adding instructions to use a priviledged account to get a working development environment. This would be highly discoured, from a security point of view. An alternative could be to run a DNS resolver for the `circles.lan` zone that is introduced, or to use subdomains from localhost.

In development of `land-local` we were very surprised when we found out that we could simply use subdomains from localhost to address individual services proxied behind the same endpoint.

Please feel free to take inspiration in https://github.com/CirclesUBI/land-local/blob/dev/modules/caddy/Caddyfile (excluding TLS handling) and consider if that could be adapted to your Docker environment: `*.circles.localhost` doesn't sound too bad, either.

Taking care of this would bring less lines of code that manage state outside of the container (here: `/etc/hosts`), and bring increased security by not needing developers to change core system components as root.

Also it may appear as a break in the levels of abstraction, when a containerised environment requires changes to its host system outside of the containers.

2023-03-16 10:00 UTC, llunaCreixent commented on README.md
> +```
that is actually not needed

2023-03-16 10:34 UTC, llunaCreixent submitted a review, later dismissed
All goooood!!
Core tests (integration) pass with pathfinder server type.

2023-03-20 12:37 UTC, llunaCreixent approved these changes
All tests patthing with both cli and server pathfinderType

2023-03-20 12:45 UTC, llunaCreixent commented
@almereyda can you review this PR? It seems there's a requested change from you blocking the merge.
Thanks! :)

2023-03-20 15:14 UTC, juanenrisley approved these changes
👍🏿

2023-03-20 15:54 UTC, merged